### ISSUE TITLE
DDP模式下可以eval吗？

### ISSUE THREAD

**Issue by 673607154** [BIGBALLON/distribuuuu#21]
hi，请教一个问题，DDP模式下可以eval吗？

**Comment by BIGBALLON** [comment]
Hi, @673607154  
Of course,  ``test_net.py`` is used to test/eval,
see https://github.com/BIGBALLON/distribuuuu/blob/master/distribuuuu/trainer.py#L176 for more details.

**Comment by 673607154** [comment]
thanks~
